name: compile and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install system packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install g++ cmake catch libocct-foundation-dev libocct-data-exchange-dev
    - name: Build
      run: |
        cmake build . -B build
        cmake --build build
    - name: Test
      run: |
        build/test_runner
