name: compile and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
    - uses: actions/checkout@v2
    - name: Install system packages
      run: |
        apt-get -y update
        apt-get -y install g++ cmake catch2 libocct-foundation-dev libocct-data-exchange-dev
    - name: Build
      run: |
        cmake build . -B build
        cmake --build build
    - name: Test
      run: |
        build/test_runner
