name: compile and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
    - uses: actions/checkout@v2
    - name: Install system packages
      run: |
        apt-get -y update
        apt-get -y install cmake python3-pip libocct-foundation-dev libocct-data-exchange-dev
    - name: Install build tools
      run: |
        pip3 install --no-cache-dir -U conan meson ninja
    - name: Configuring Conan
      run: |
        conan config init
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Build
      run: |
        CXXFLAGS=-I/usr/include/opencascade meson setup build
        meson test -vC build
    - name: Test
      run: |
        ninja -C build test
