name: compile and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
    - name: Install system packages
      run: |
        apt-get -y update
        apt-get -y install git git-lfs g++ cmake libocct-foundation-dev libocct-data-exchange-dev
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive
    - name: Build
      run: |
        git submodule update
        cmake build . -B build -DWERROR=ON
        cmake --build build
    - name: Install
      run: |
        cmake --install build
    - name: Test
      run: |
        env -C build ctest --output-on-failure
