name: compile and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-21.04
    steps:
    - uses: actions/checkout@v2
    - name: Install system packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libocct-foundation-dev libocct-data-exchange-dev
    - name: Install build tools
      run: |
        python -m pip install -U conan meson ninja
    - name: Install dependencies via Conan
      run: |
        conan install --build=fmt fmt/8.0.1@
        conan install --build=spdlog spdlog/1.9.2@
        conan install --build=cli11 cli11/2.0.0@
        conan install --build=doctest doctest/2.4.6@
    - name: Build
      run: |
        meson setup build
        ninja -C build
